[package]
name = "Bres"
version = "0.1.0"
authors = ["Artem Rogov <rogovartemalex@gmail.com>"]
edition = "2018"

[dependencies]
image = "0.18.0"
nalgebra = "0.14.1"

[profile.dev]
opt-level = 2
debug = true
incremental = true
overflow-checks = false
